name: fun-ts-elmish build

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                node-version: [18.14.1]

        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2
              with:
                  version: 7.27.1

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"

            - run: pnpm install --frozen-lockfile
            - run: pnpm run build
            - run: pnpm run lint
            - run: pnpm run deliver
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
